apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node-express-postgres
  annotations:
    github.com/project-slug: Namrathaputrev/node-express-postgres
spec:
  type: other
  lifecycle: unknown
  owner: guests
